name: DeployRunbook
on:  
    workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  DeployRunbooks:
    name: Create Runbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      
      - name: Azure Login        
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      - name: Set PSRepo
        shell: pwsh
        run: |
             Set-PSRepository PSGallery -InstallationPolicy Trusted
      - name: Install Modules
        shell: pwsh
        run: |
             Install-Module Az.Accounts
             Install-Module Az.Automation
             Install-Module Az.Resources
      - name: Execute Power Shell
        shell: pwsh
        run: |
             .\Runbook\DeployRunBook.ps1 'mm212912aa' 'mm212912' 'neu-demo-wu2-da-syn-01' 'neudemowu2dapool01' 'neudemowu2dasql01.database.windows.net' 'neudemodawu2aas01' 'neu-demo-wu2-da-kv-01'
